# Generated by Django 5.1.6 on 2025-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mail_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Sending', 'Sending'), ('Created', 'Created')], default='Created', max_length=55),
        ),
    ]
