# Generated by Django 5.1.6 on 2025-02-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error')], max_length=55),
        ),
    ]
